### ISSUE TITLE
Dual Mah-Jong priority

### ISSUE THREAD

**Issue by magicfoxt-magicfox** [passcod/mah-jong#29]
xmj version 1.11 on current Ubuntu

It's seems to me that the east wind must have the priority in this case of north and east have Mah-Jong at the same time, but it's not the case (see capture) :(

![dual-mah-jong](https://github.com/passcod/mah-jong/assets/121636800/a381ced7-16b2-4198-8cc7-c8fbc19298ed)

**Comment by magicfoxt-magicfox** [comment]
_Note:_ Mah-jong is done with seven circle title

**Comment by passcod** [comment]
I'm not the original author of the code, this is merely an outdated source mirror. See [mahjong.julianbradfield.org](http://mahjong.julianbradfield.org/).
